#!/bin/bash

#SBATCH --partition=gpu_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=TrainAAE
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=01:00:00
#SBATCH --mem=32000M
#SBATCH --output=TrainAAE_lambd1_zdim2_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

# Activate your environment
source activate dl2022
# Run your code
srun python -u train.py --data_dir $TMPDIR/ --z_dim 2 --log_dir 'lamnd1z_dim2/' --lambda_ 1 --ae_lr 1e-4
